# Introduction au machine learning : Utiliser un modèle entraîné

Laurent Cetinsoy

Avant d'entraîner nos propres modèles, on va essayer de comprendre comment utiliser un modèle de machine learning déjà entraîné. Cela nous permettra de mieux saisir ce que calcule un modèle. 

Rappel : Un modèle de machine learning est une fonction souvent notée $ X \rightarrow f_\theta(X) $ qui produit une prédiction. 

Dans le cas du machine learning supervisé on peut avoir deux types de prédictions :

- quand les valeurs sont des nombres réels: la température, un montant, la pression, etc. Il s'agit alors de régression
- quand les valeurs sont des nombres discrets et représentent des catégories : il s'agit de classification 



## utilisation d'une modèle de régression linéaire pour la prédiction du prix d'une maison

On va charger un fichier qui contient une modèle de prédiction de prix déjà entraîné avec la librairie joblib


In [ ]:
import joblib

model = joblib.load('regression.joblib')

type(model)

sklearn.linear_model._base.LinearRegression

Maintenant qu'on a chargé le modèle on va pouvoir calculer le prix des prédictions de prix de maisons à partir de ses caractéristiques. 

Le modèle utilise les caractéristiques suivantes pour prédire le prix d'une maison : 

- la taille
- le nombre de chambre
- si la maison a un jardin ou non

il faut donc lui donner les informations pour avoir la prédiction 


In [ ]:
X = np.array([[
    110, 3, 0 #maison de 110 metre carré avec trois chambre et pas de jardin
]])


prix_predits = model.predict(X)
prix_predits

array([140000.])

On peut faire plusieurs prédictions d'un coup si on veut 


In [ ]:
X = np.array([
    [110, 3, 0], #maison de 110 metre carré avec trois chambre et pas de jardin
    [80, 2, 1],
    [150, 4, 1]
])

prix_predits = model.predict(X)
prix_predits

array([140000., 120000., 210000.])

## Evaluer la performance d'un modele 

Ok notre modèle fait des prédictions, mais sont-elles bonnes ? 


Supposons qu'on dispose pour certaines maisons des vrais prix. On va comparer



In [ ]:
prix_reels = np.array([
    139000, 120001, 220000
])

In [ ]:
#calculons les écarts

ecart = prix_predits - prix_reels
print(ecart)
ecart_carre = ecart ** 2

ecart_moyen = ecart_carre.mean()
ecart_moyen
np.sqrt(ecart_moyen)

[ 1.e+03 -1.e+00 -1.e+04]


5802.298423900589

On constate que les prédictions ne sont pas trop éloignée et cela se traduit par le fait que la Mean squared error est faible. 

En général la racine carrée de la mean square error permet d'avoir un écart qui soit dans la même dimension que les prédictions. Ainsi une écart de 5000 € pour des maisons à plus de 100 000 € est raisonnable. 

Un bon modèle est un modèle qui fait des bonnes prédictions

Nous reviendrons sur ce sujet. 

Maintenant qu'on qu'on a un bon modèle on va l'utiliser dans une application 

Instructions : 

1. installer streamlit : pip install streamlit
2. récupérer le fichier 14.1 application_prediction_prix.py et le fichier regression.joblib
3. Lancer avec l'application avec la commande streamlit run 14.1 application_prediction_prix.py
4. Appreciez cette belle application
5. Regarder le code du fichier et tacher de comprendre ce que ça fait


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=25ad01f7-ec4b-4ac8-bce6-a3745ef02c96' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>